# Generated by Django 5.2.6 on 2025-11-05 22:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Classe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                (
                    "niveau",
                    models.CharField(help_text="Ex: Collège, Lycée", max_length=50),
                ),
            ],
            options={
                "verbose_name": "Classe",
                "verbose_name_plural": "Classes",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="ProduitStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200, unique=True)),
                (
                    "unite",
                    models.CharField(
                        choices=[
                            ("KG", "Kilogramme"),
                            ("L", "Litre"),
                            ("UNITE", "Unité"),
                            ("SAC", "Sac"),
                            ("CARTON", "Carton"),
                        ],
                        default="KG",
                        max_length=20,
                    ),
                ),
                (
                    "quantite_stock",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "seuil_alerte",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Seuil en dessous duquel une alerte est déclenchée",
                        max_digits=10,
                    ),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Produit en stock",
                "verbose_name_plural": "Produits en stock",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Eleve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prenom", models.CharField(max_length=100)),
                ("nom", models.CharField(max_length=100)),
                ("date_inscription", models.DateField(auto_now_add=True)),
                (
                    "actif",
                    models.BooleanField(
                        default=True,
                        help_text="Élève actuellement inscrit à la cantine",
                    ),
                ),
                (
                    "solde",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Solde actuel en FCFA",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("telephone_parent", models.CharField(blank=True, max_length=20)),
                ("email_parent", models.EmailField(blank=True, max_length=254)),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Notes supplémentaires"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "classe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cantine_web.classe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Élève",
                "verbose_name_plural": "Élèves",
                "ordering": ["classe", "nom", "prenom"],
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "jour_semaine",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LUNDI", "Lundi"),
                            ("MARDI", "Mardi"),
                            ("MERCREDI", "Mercredi"),
                            ("JEUDI", "Jeudi"),
                            ("VENDREDI", "Vendredi"),
                            ("SAMEDI", "Samedi"),
                        ],
                        max_length=10,
                    ),
                ),
                ("plat_principal", models.CharField(max_length=200)),
                ("accompagnement", models.CharField(blank=True, max_length=200)),
                ("dessert", models.CharField(blank=True, max_length=200)),
                (
                    "prix",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Prix du repas en FCFA",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("disponible", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Menu",
                "verbose_name_plural": "Menus",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["date"], name="cantine_web_date_729f87_idx"),
                    models.Index(
                        fields=["disponible"], name="cantine_web_disponi_bf8304_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "type_paiement",
                    models.CharField(
                        choices=[
                            ("ESPECES", "Espèces"),
                            ("VIREMENT", "Virement"),
                            ("CHEQUE", "Chèque"),
                            ("CARTE", "Carte bancaire"),
                        ],
                        default="ESPECES",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "reference",
                    models.CharField(
                        blank=True, help_text="Référence du paiement", max_length=100
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paiements_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cantine_web.eleve",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MouvementStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_mouvement",
                    models.CharField(
                        choices=[("ENTREE", "Entrée"), ("SORTIE", "Sortie")],
                        max_length=10,
                    ),
                ),
                (
                    "quantite",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "raison",
                    models.CharField(
                        blank=True, help_text="Raison du mouvement", max_length=200
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mouvements_stock_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cantine_web.produitstock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mouvement de stock",
                "verbose_name_plural": "Mouvements de stock",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Repas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "prix_paye",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cantine_web.eleve",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cantine_web.menu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Repas",
                "verbose_name_plural": "Repas",
                "ordering": ["-date", "eleve"],
            },
        ),
        migrations.CreateModel(
            name="Depense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=200)),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("ACHAT_PROVISIONS", "Achat de provisions"),
                            ("GAZ", "Gaz"),
                            ("EAU", "Eau"),
                            ("ELECTRICITE", "Électricité"),
                            ("SALAIRE", "Salaire personnel"),
                            ("ENTRETIEN", "Entretien"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=50,
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "facture",
                    models.FileField(blank=True, null=True, upload_to="factures/"),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="depenses_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dépense",
                "verbose_name_plural": "Dépenses",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(fields=["date"], name="cantine_web_date_806e68_idx"),
                    models.Index(
                        fields=["categorie", "date"],
                        name="cantine_web_categor_4f1ce1_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="eleve",
            index=models.Index(
                fields=["nom", "prenom"], name="cantine_web_nom_a46acc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eleve",
            index=models.Index(fields=["actif"], name="cantine_web_actif_2cf92d_idx"),
        ),
        migrations.AddIndex(
            model_name="paiement",
            index=models.Index(
                fields=["eleve", "date"], name="cantine_web_eleve_i_cdbba1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paiement",
            index=models.Index(fields=["date"], name="cantine_web_date_9f6e75_idx"),
        ),
        migrations.AddIndex(
            model_name="mouvementstock",
            index=models.Index(
                fields=["produit", "date"], name="cantine_web_produit_944499_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mouvementstock",
            index=models.Index(fields=["date"], name="cantine_web_date_8736d1_idx"),
        ),
        migrations.AddIndex(
            model_name="repas",
            index=models.Index(fields=["date"], name="cantine_web_date_401739_idx"),
        ),
        migrations.AddIndex(
            model_name="repas",
            index=models.Index(
                fields=["eleve", "date"], name="cantine_web_eleve_i_546f1f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="repas",
            unique_together={("eleve", "date")},
        ),
    ]
