# Generated by Django 5.2.6 on 2025-11-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cantine_web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eleve",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Photo de profil de l'élève",
                null=True,
                upload_to="eleves/",
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="image",
            field=models.ImageField(
                blank=True, help_text="Image du menu", null=True, upload_to="menus/"
            ),
        ),
    ]
