# Generated by Django 5.2.6 on 2025-11-06 00:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cantine_web", "0002_eleve_photo_menu_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mouvementstock",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="mouvementstock",
            name="produit",
        ),
        migrations.RemoveField(
            model_name="paiement",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="paiement",
            name="eleve",
        ),
        migrations.RemoveField(
            model_name="eleve",
            name="solde",
        ),
        migrations.RemoveField(
            model_name="repas",
            name="prix_paye",
        ),
        migrations.AddField(
            model_name="repas",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="repas_crees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Facture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        help_text="Numéro de facture", max_length=50, unique=True
                    ),
                ),
                ("annee", models.IntegerField()),
                (
                    "mois",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                (
                    "nombre_jours_travail",
                    models.IntegerField(
                        default=0, help_text="Nombre de jours travaillés dans le mois"
                    ),
                ),
                ("nombre_repas_servis", models.IntegerField(default=0)),
                (
                    "prix_unitaire_repas",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Prix unitaire d'un repas en FCFA",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "montant_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("ENVOYEE", "Envoyée"),
                            ("PAYEE", "Payée"),
                            ("ANNULEE", "Annulée"),
                        ],
                        default="BROUILLON",
                        max_length=20,
                    ),
                ),
                ("date_emission", models.DateField(default=django.utils.timezone.now)),
                ("date_paiement", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="factures_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture",
                "verbose_name_plural": "Factures",
                "ordering": ["-annee", "-mois", "-date_emission"],
            },
        ),
        migrations.CreateModel(
            name="InscriptionMensuelle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee", models.IntegerField()),
                (
                    "mois",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("inscrit", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inscriptions_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscriptions_mensuelles",
                        to="cantine_web.eleve",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription Mensuelle",
                "verbose_name_plural": "Inscriptions Mensuelles",
                "ordering": ["-annee", "-mois", "eleve"],
            },
        ),
        migrations.CreateModel(
            name="ProfilPrestataire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrateur"),
                            ("PRESTATAIRE", "Prestataire"),
                        ],
                        default="PRESTATAIRE",
                        max_length=20,
                    ),
                ),
                ("telephone", models.CharField(blank=True, max_length=20)),
                (
                    "entreprise",
                    models.CharField(
                        blank=True,
                        help_text="Nom de l'entreprise prestataire",
                        max_length=200,
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil Prestataire",
                "verbose_name_plural": "Profils Prestataires",
            },
        ),
        migrations.DeleteModel(
            name="Depense",
        ),
        migrations.DeleteModel(
            name="MouvementStock",
        ),
        migrations.DeleteModel(
            name="ProduitStock",
        ),
        migrations.DeleteModel(
            name="Paiement",
        ),
        migrations.AddIndex(
            model_name="facture",
            index=models.Index(
                fields=["annee", "mois"], name="cantine_web_annee_78bf04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="facture",
            index=models.Index(fields=["statut"], name="cantine_web_statut_2e9a6f_idx"),
        ),
        migrations.AddIndex(
            model_name="inscriptionmensuelle",
            index=models.Index(
                fields=["annee", "mois"], name="cantine_web_annee_38b620_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inscriptionmensuelle",
            index=models.Index(
                fields=["eleve", "annee", "mois"], name="cantine_web_eleve_i_2ed5ac_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inscriptionmensuelle",
            unique_together={("eleve", "annee", "mois")},
        ),
    ]
