# Generated by Django 5.2.6 on 2025-11-06 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cantine_web", "0003_remove_mouvementstock_created_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="prix",
        ),
    ]
