# Generated by Django 5.2.6 on 2025-11-06 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cantine_web", "0004_remove_menu_prix"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="classe",
            options={
                "ordering": ["nom"],
                "verbose_name": "Class",
                "verbose_name_plural": "Classes",
            },
        ),
        migrations.AlterModelOptions(
            name="eleve",
            options={
                "ordering": ["classe", "nom", "prenom"],
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
            },
        ),
        migrations.AlterModelOptions(
            name="facture",
            options={
                "ordering": ["-annee", "-mois", "-date_emission"],
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
            },
        ),
        migrations.AlterModelOptions(
            name="inscriptionmensuelle",
            options={
                "ordering": ["-annee", "-mois", "eleve"],
                "verbose_name": "Monthly Registration",
                "verbose_name_plural": "Monthly Registrations",
            },
        ),
        migrations.AlterModelOptions(
            name="profilprestataire",
            options={
                "verbose_name": "Provider Profile",
                "verbose_name_plural": "Provider Profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="repas",
            options={
                "ordering": ["-date", "eleve"],
                "verbose_name": "Meal",
                "verbose_name_plural": "Meals",
            },
        ),
        migrations.CreateModel(
            name="ActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Création"),
                            ("UPDATE", "Modification"),
                            ("DELETE", "Suppression"),
                            ("VIEW", "Consultation"),
                            ("EXPORT", "Export"),
                            ("IMPORT", "Import"),
                            ("LOGIN", "Connexion"),
                            ("LOGOUT", "Déconnexion"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Nom du modèle concerné", max_length=100
                    ),
                ),
                (
                    "object_id",
                    models.IntegerField(
                        blank=True, help_text="ID de l'objet concerné", null=True
                    ),
                ),
                ("description", models.TextField(help_text="Description de l'action")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Action Log",
                "verbose_name_plural": "Action Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="cantine_web_user_id_5e89ec_idx",
                    ),
                    models.Index(
                        fields=["action_type", "created_at"],
                        name="cantine_web_action__e1c10d_idx",
                    ),
                    models.Index(
                        fields=["model_name"], name="cantine_web_model_n_94d94a_idx"
                    ),
                ],
            },
        ),
    ]
